name: PreventArmor
version: '${version}'
main: org.eyman_.preventarmor
api-version: '1.21'
author: Eyman
description: Damages (and optionally strips) players who wear armor.

commands:
  preventarmor:
    description: Reloads the PreventArmor config
    usage: /preventarmor reload
    permission: preventarmor.reload

permissions:
  preventarmor.reload:
    description: Allows reloading the PreventArmor config
    default: op
